sudo: false
language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
before_script:
  - npm install standard
  - standard
script:
  - npm install istanbul
  - istanbul cover test.js --report lcovonly
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls